name: mlops_production
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10.13
  
  # Core API Framework (Pydantic v2 compatible)
  - fastapi=0.115.0
  - uvicorn=0.30.0
  
  # Machine Learning Core
  - scikit-learn=1.4.0
  - numpy=1.26.3
  - pandas=2.1.4
  - scipy=1.12.0
  
  # Gradient Boosting Models
  - xgboost=2.0.3
  - lightgbm=4.3.0
  
  # Data Processing
  - joblib=1.3.2
  - openpyxl=3.1.2
  
  # Utilities
  - pyyaml=6.0.1
  - python-dotenv=1.0.0
  - requests=2.31.0
  
  # Code Quality
  - black=24.2.0
  - flake8=7.0.0
  
  # Pip packages
  - pip=24.0
  - pip:
    # Pydantic v2 and settings (MUST be v2 for FastAPI 0.115+)
    - pydantic==2.8.2
    - pydantic-settings==2.3.4
    
    # CatBoost
    - catboost==1.2.5
    
    # MLflow (compatible with Pydantic v2)
    - mlflow==2.14.3
    
    # Evidently AI (v0.5.0+ supports Pydantic v2)
    - evidently==0.5.1
    
    # Data Validation
    - great-expectations==0.18.19
    
    # Lightweight Scheduler
    - schedule==1.2.2
    
    # API Testing
    - httpx==0.27.0
    
    # Logging & Monitoring
    - python-json-logger==2.0.7
    - prometheus-client==0.20.0
    - prometheus-fastapi-instrumentator==7.1.0
    
    # Type Checking
    - mypy==1.10.0
    
    # Jupyter Notebook Execution
    - papermill==2.6.0